# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('download_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='seasons',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Seasons'),
        ),
    ]
